### ISSUE TITLE
USER STORY: Initial Setup

### ISSUE THREAD

**Issue by pzompa** [pzompa/pp5_tibet_art_store#2]
As a **Developer** I want to **install Django** so that **my project can be created**

---

**Tasks**
- [ ] Tasks : Install Django Framework
- [ ] Tasks 2: Install Gunicorn HTTP server
- [ ] Tasks 3: Install supporting libraries

---
