### ISSUE TITLE
USER STORY: Create Homepage and header content

### ISSUE THREAD

**Issue by pzompa** [pzompa/pp5_tibet_art_store#4]
As a **user** I want to **see an appealing visual and navigate across the site easily** so that **I can browse the content and buy them if needed**

---

**Acceptance Criteria**:

  - Acceptance Criteria 1: The user lands on the homepage with the site logo without having to log in.
  - Acceptance Criteria 2: The user is able to see the navigation menu with working links to all other pages.
  - Acceptance Criteria 3: The user is also able to see the search button
 
---

**Tasks**
- [ ] Task 1: Create the homepage html template.
- [ ] Task 2: Add style to the template with bootstrap classes and custom css.
- [ ] Task 3: Add Logo, navigation menu with search function.

---
